### ISSUE TITLE
`/bin/sh: syntax error: unexpected "}"` when building for v3.18 and `sudo`

### ISSUE THREAD

**Issue by ShaneMcC** [dermotbradley/create-alpine-disk-image#47]
When attempting to build for v3.18 using `sudo` rather than `doas`,  the script fails with:
```
/bin/sh: syntax error: unexpected "}"
```

This is because `additional_os_configuration()` generates an empty section:

```
write_log "Doing additional OS configuration"
{
}
```

Moving the `write_log` line inside the `{}` section resolves the problem.

**Comment by dermotbradley** [comment]
Yeah I'd missed this as I hadn't tested sudo for a while (Alpine prefers doas to sudo these days).

Fixed in the most recent PR merged.
